version: '3.8'
services:
  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./env/mysql.env
    container_name: mysql
    restart: always
#    platform: linux/amd64 # "${FRAMEWORK}" # linux/amd64 for M1 Mac
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '8080:8080'
#    platform: linux/amd64 # linux/amd64 for M1 Mac
    restart: always
    stdin_open: true
    tty: true
