version: '3.8'
services:
  mysql:
    extends:
      file: common-service.yaml
      service: mysql
    ports:
      - '3307:3306' # expose this only for outside access, to get db data
    stdin_open: true
    tty: true
  backend:
    extends:
      file: common-service.yaml
      service: backend
    build:
      args:
        - PROFILE=dev
        - PORT=8080
    depends_on:
      - mysql
# try to avoid network_mode: host, because it will cause mysql container can't be accessed from outside
#    network_mode: host