version: '3.8'
services:
  mysql:
    extends:
      file: common-service.yaml
      service: mysql
    ports:
      - '3307:3306' # expose this only for outside access, to get db data
  backend:
    extends:
      file: common-service.yaml
      service: backend
    build:
      args:
        - PROFILE=dev
    depends_on:
      - mysql