version: '3.8'
services:
  mysql:
    extends:
      file: common-service.yaml
      service: mysql
  backend:
    extends:
      file: common-service.yaml
      service: backend
    build:
      args:
        - PROFILE=test
    depends_on:
      - mysql
