# for local, only start mysql container, then run backend app
spring:
  config:
    activate:
      on-profile: dev
  datasource:
#    url: jdbc:mysql://localhost:3307/employee?useSSL=false
#   it is better to use host.docker.internal instead of localhost
    url: jdbc:mysql://host.docker.internal:3307/employee?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080