# for local, only start mysql container, then run backend app
spring:
  config:
    activate:
      on-profile: dev
  port: 8080
  datasource:
    url: jdbc:mysql://localhost:3307/employee?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect