version: '3.8'
services:
  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 123456
      MYSQL_USER: employee
      MYSQL_PASSWORD: 123456
    ports:
      - '3307:3306'
#    volumes:
#      - ./mysql:/var/lib/mysql
#  backend:
#      build:
#        context: .
#        dockerfile: Dockerfile
#      container_name: backend
#      restart: always
#      stdin_open: true
#      tty: true
#      network_mode: host